# .pre-commit-config.yaml
ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

# If you want hooks to run only when you invoke them manually, uncomment:
# default_stages: [manual]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0  # or run `pre-commit autoupdate` to bump this
    hooks:
      - id: ruff
        # optional: auto-fix lint issues
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: check-i18n-keys
        name: Check i18n keys match across locales
        entry: python scripts/check_i18n_keys.py
        language: system
        files: ^lang/.*\.json$
        pass_filenames: false
