name: Security Scan (Bandit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: python -m pip install --upgrade pip bandit

      # 1) Generate a full report (never fails the job) so you can review details
      - name: Bandit full report (non-blocking)
        run: |
          bandit -r . \
            -x tests,venv,.venv,build,dist,__pycache__,.github \
            -s B101,B404 \
            -f txt -o bandit.txt || true

      # 2) Gate on HIGH severity + HIGH confidence only (job fails if any)
      - name: Bandit gate (HIGH/HIGH only)
        run: |
          bandit -q -r . \
            -x tests,venv,.venv,build,dist,__pycache__,.github \
            -s B101,B404 \
            --severity-level high --confidence-level high

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit.txt
          if-no-files-found: warn
          retention-days: 7
