name: Security Scan (Bandit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # needed for SARIF upload
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: python -m pip install --upgrade pip bandit

      # Full report for triage (non-blocking), goes to the Security tab
      - name: Bandit SARIF (non-blocking)
        run: |
          bandit -r . \
            -x tests,venv,.venv,build,dist,__pycache__,.github \
            -f sarif -o bandit.sarif || true

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
          category: bandit

      # Gate 1: fail on ANY High severity (even if confidence is low)
      - name: Bandit gate — HIGH severity (any confidence)
        run: |
          bandit -q -r . \
            -x tests,venv,.venv,build,dist,__pycache__,.github \
            --severity-level high --confidence-level low

      # Gate 2: fail on Medium/High with HIGH confidence
      - name: Bandit gate — MEDIUM+ with HIGH confidence
        run: |
          bandit -q -r . \
            -x tests,venv,.venv,build,dist,__pycache__,.github \
            --severity-level medium --confidence-level high
